# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iR_ShQNS_WcICFJraNOasuNd4prSWueI
"""

import pandas as pd

Data = pd.read_csv('/content/lending_club_loan_two.csv')

#Data profiling
Data.shape

Data.info()

Data.head()

#always find target column
Data['loan_status'].value_counts()

Data['loan_status'] = Data['loan_status'].replace({
    'Fully Paid': 0,
    'Charged Off': 1
})

Data['loan_status'].value_counts()

#missing Value Handling
Data.isnull().sum()

Data['emp_title'].value_counts()

Data.drop('emp_title', axis=1, inplace=True)

Data['emp_length'].value_counts()

Data['emp_length'].fillna(Data['emp_length'].mode()[0], inplace=True)

Data['emp_length'] = Data['emp_length'].astype(str)

Data['emp_length'] = Data['emp_length'].str.replace('+ years', '', regex=False)
Data['emp_length'] = Data['emp_length'].str.replace('< 1 year', '0', regex=False)

Data['emp_length'] = Data['emp_length'].str.extract(r'(\d+)')
Data['emp_length'] = Data['emp_length'].astype(float)

Data['mort_acc'].value_counts()

Data['mort_acc'] = Data['mort_acc'].fillna(Data['mort_acc'].median())

Data.isnull().sum()

#Drop other all missing Columns
Data.dropna()

Data.shape

#Duplicate Handling
Data.duplicated().sum()

#Data type conversion
Data['term'] = Data['term'].astype(str).str.extract(r'(\d+)').astype(int)

Data['earliest_cr_line'] = pd.to_datetime(Data['earliest_cr_line'])

# Drop Irrelevent Column
Data.drop(['address', 'title'], axis=1, inplace=True)

#Add some new column
Data['credit_history_years'] = 2025 - Data['earliest_cr_line'].dt.year

Data['loan_income_ratio'] = Data['loan_amnt'] / Data['annual_inc']

Data['credit_utilization'] = Data['revol_bal'] / Data['annual_inc']

#Some Outlier Handling
Data = Data[Data['annual_inc'] < Data['annual_inc'].quantile(0.99)]
Data = Data[Data['loan_amnt'] < Data['loan_amnt'].quantile(0.99)]

Data.shape

Data.info()

Data.to_csv('Cleaned Dataset.csv')

